[build]
  command = "ng build --configuration production && ng run {projectName}:serverless:production"
  publish = "dist/{projectName}/browser"
[build.environment]
   projectName = "hecta"

[[plugins]]
  package = "@netlify/plugin-angular-universal"
  [plugins.inputs]
  projectName = "hecta"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

