[build]
  command = "npm run prerender -- --c production && ng run hecta:serverless:production"
  publish = "dist/project-name/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[[redirects]]
  from = "/*"
  to = "/index.html"df
  status = 200