<<<<<<< HEAD
=======

>>>>>>> d3f1e6edbec7541c30cc3fe694749541ff4b9e03
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
<<<<<<< HEAD
=======

>>>>>>> d3f1e6edbec7541c30cc3fe694749541ff4b9e03
