[build]
  command = "ng build --configuration production && ng run {projectName}:serverless:production"
  publish = "dist/{projectName}/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"
  inputs: {
  projectName:"hecta"
  }
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

