[build]
  command = "npm run prerender --c production && ng run {projectName}:serverless:production"
  publish = "dist/{projectName}/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[plugins.inputs]
  projectName = "hecta"
