[build]
  command = "npm run prerender --c production && ng run hecta:serverless:production"
  publish = "dist/hecta/browser"

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[plugins.inputs]
  projectName = "hecta"