[build]
command = "ng build --configuration production && ng run angular-universal:serverless:production"
publish = "dist/angular-universal/browser"

[[plugins]]
package = "@netlify/plugin-angular-universal"