[build]
  base="/"
  command = "ng build --configuration production && ng run hecta:serverless:production"
  publish = "dist/hecta/browser"


[[plugins]]
  package = "@netlify/plugin-angular-universal"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

